### ISSUE TITLE
checked files count

### ISSUE THREAD

**Issue by rianquinn** [dalance/flexlint#7]
The total number of checked files doesn't seem to show checked files... it shows files that matched the pattern. 

Would it be possible to show stats on what was actually checked so that we can prove that all of the files were parsed? For example, if I have 5 files, I would expect something like:

```
- Summary ----------------------------------------------------------------------

  * Checked files : 5
  * Checked points: 1 ( Pass: 0, Fail: 1, Skip: 0 )
  * Elapsed time  : 0.000073s
```

Right now... checked files is 1, even though 5 were actually checked.

**Comment by dalance** [comment]
Thank you for your report. I fixed it and released as v0.2.5.
